#!/usr/bin/env bash


user=""       # username on remote host
maxNodes=""   # the number of onion router nodes to set up
dirCebolla="" # the path to the root of the Cebolla directory
branch=       # the git branch to checkout on remote host
while getopts "m:u:d:" opt
do
    case "$opt" in
        m)
            maxNodes="$OPTARG"
            ;;
        u)
            user="$OPTARG"
            ;;
        d)
            dirCebolla="$OPTARG"
            ;;
    esac
done


for i in $(seq 1 "$maxNodes")
do
    servername="lab2-$i.cs.mcgill.ca"
    # use version on github branch
    ssh "$user"@"$servername" \
        "cd $dirCebolla;
         git clone https://github.com/CamiloGarciaLaRotta/Cebolla/ ~/Documents/Cebolla;"
done
